#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOC_TEST_DIR="${ROOT_DIR}/doc_tests"
TYPST_BIN="${TYPST_BIN:-typst}"
DIAG_FORMAT="${DIAG_FORMAT:-short}"
OUTPUT_SUFFIX=".teco.pdf"
META_FILE="${DOC_TEST_DIR}/meta.teco.typ"
CHECK_ONLY=false
OPEN_RESULT=false
FILTER_PATTERN=""
LANG_SPEC="${TEST_LANGS:-}"

usage() {
  cat <<EOF
Usage: $(basename "$0") [options]

Runs Typst compilation for each .typ test in ${DOC_TEST_DIR}.
Outputs are written next to the input files with a ${OUTPUT_SUFFIX} suffix.

Options:
  -f, --filter <pattern>  Only run tests whose filename matches the pattern (regex).
  -l, --langs <list>      Comma-separated list of language codes to test (e.g. "en-at,de-at,de-de").
  -c, --check             Compile to a temporary file and discard the output (fast dry run).
  -o, --open              Pass --open to Typst for quick inspection of results.
  -h, --help              Show this help message.

You can override the Typst binary via TYPST_BIN and the diagnostic format via DIAG_FORMAT.
EOF
}

log() {
  printf '[run_tests] %s\n' "$*"
}

write_meta() {
  local langs_input="$1"
  local langs=()

  if [[ -n "${langs_input}" ]]; then
    IFS=',' read -r -a langs <<< "${langs_input}"
  else
    langs=(en-at en-de en-us de-at de-de)
  fi

  {
    echo "// Auto-generated by run_tests.sh; do not edit manually."
    echo ""
    echo "#let test-languages = ("
    for lang in "${langs[@]}"; do
      echo "  \"${lang}\","
    done
    echo ")"
  } > "${META_FILE}"
}

run_test() {
  local input="$1"
  local base="${input%.typ}"
  local output="${base}${OUTPUT_SUFFIX}"
  local target="${output}"
  local cmd=(
    "${TYPST_BIN}" compile
    --root "${ROOT_DIR}"
    --diagnostic-format "${DIAG_FORMAT}"
  )

  if [[ "${OPEN_RESULT}" == true && "${CHECK_ONLY}" == false ]]; then
    cmd+=(--open)
  fi

  if [[ "${CHECK_ONLY}" == true ]]; then
    target="$(mktemp -p "${DOC_TEST_DIR}" "doc_test.XXXXXX${OUTPUT_SUFFIX}")"
    log "Compiling ${input} (check mode -> ${target})"
  else
    log "Compiling ${input}"
  fi

  cmd+=("${input}" "${target}")

  "${cmd[@]}"

  if [[ "${CHECK_ONLY}" == true ]]; then
    rm -f "${target}"
  fi
}

list_tests() {
  find "${DOC_TEST_DIR}" -maxdepth 1 -type f -name '*.typ' ! -name '*.teco.typ' -print | sort
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    -f|--filter)
      FILTER_PATTERN="$2"
      shift 2
      ;;
    -l|--langs)
      LANG_SPEC="$2"
      shift 2
      ;;
    -c|--check)
      CHECK_ONLY=true
      shift
      ;;
    -o|--open)
      OPEN_RESULT=true
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      usage
      exit 1
      ;;
  esac
done

mapfile -t TEST_FILES < <(list_tests)

if [[ -n "${FILTER_PATTERN}" ]]; then
  mapfile -t TEST_FILES < <(printf '%s\n' "${TEST_FILES[@]}" | grep -E "${FILTER_PATTERN}" || true)
fi

if [[ ${#TEST_FILES[@]} -eq 0 ]]; then
  log "No test files found in ${DOC_TEST_DIR} (filter='${FILTER_PATTERN}')."
  exit 1
fi

write_meta "${LANG_SPEC}"

for test_file in "${TEST_FILES[@]}"; do
  run_test "${test_file}"
done
